# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('mini_image_title', models.ImageField(upload_to='')),
                ('first_image_comp', models.ImageField(upload_to='')),
                ('first_or_lending_image', models.ImageField(upload_to='')),
                ('second_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
