# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomodel',
            name='first_image_comp',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='first_or_lending_image',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='mini_image_title',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='second_image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
