# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20161223_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomodel',
            name='first_image_comp',
            field=models.ImageField(upload_to='/static/images/'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='first_or_lending_image',
            field=models.ImageField(upload_to='/static/images/'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='mini_image_title',
            field=models.ImageField(upload_to='/static/images/'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='second_image',
            field=models.ImageField(upload_to='/static/images/'),
        ),
    ]
