# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_auto_20170102_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=254)),
                ('create_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoInMainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField()),
                ('avatar', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='first_image_comp',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='first_or_lending_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='mini_image_title',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='second_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
