# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_auto_20170122_1441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
