# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomodel',
            name='second_image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
